# Generated by Django 3.0.5 on 2020-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20201209_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'None of the time'), ('2', 'Rarely'), ('3', 'Some of the time'), ('4', 'Often'), ('5', 'All of the time')], max_length=20, null=True),
        ),
    ]
