# Generated by Django 3.0.5 on 2020-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20201216_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_tai_chyi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
