# Generated by Django 3.0.5 on 2020-12-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20201217_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=2, null=True),
        ),
    ]
